services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_DB=appdb"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: spring-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  pg:
    image: eclipse-temurin:21-jre
    container_name: pg
    volumes:
      - ./pg/pg-0.0.1-SNAPSHOT.jar:/app/pg.jar
    command: ["java", "-jar", "/app/pg.jar"]
    ports:
      - "9090:9090"

volumes:
  postgresdata: